theme: ./paper

siteConfig:
  title: Paper
  description: A theme for saber.js
  url: https://saber.chenxixian.cn
  author: chenxixian

permalinks:
  post: /:year/:month/:day/:slug

themeConfig:
  nav:
    - title: About
      link: /about.html
    - title: Example
      link: /example.html
    - title: Example2
      link: /example2.html
    - title: Tags
      link: /tags.html

  # The Home section on sidebar (mobile)
  spHome:
    title: Home
    link: /

markdown:
  highlighter: prism

plugins:

  - resolve: saber-plugin-feed
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-generate-feed
    options:
      atomFeed: true

